version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t private-blockchain:0.0.1 .
      - run:
          name: Test
          command: docker run private-blockchain:0.0.1 npm run test

workflows:
  version: 2
  deploy-private-blockchain:
    jobs:
      - build-and-test
