version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t private-blockchain:0.0.1 .

workflows:
  version: 2
  build:
    jobs:
      - build